/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.drongox.gildedrose;

import org.junit.Test;

import static org.junit.Assert.*;


public class GildedRoseTest
{
  @Test
  public void testOmarIsInTheRoom()
  {
    throw new OutOfMemoryError("Omar c'est ta faute!!!!!!");
  }
}
